// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: empmgmt/empmgmt.proto

package exercise

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeDatabaseCrudClient is the client API for EmployeeDatabaseCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeDatabaseCrudClient interface {
	CreateEmployee(ctx context.Context, in *NewEmp, opts ...grpc.CallOption) (*Emp, error)
	GetEmployees(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Emps, error)
	UpdateEmployee(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*Emp, error)
	DeleteEmployee(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*Response, error)
}

type employeeDatabaseCrudClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeDatabaseCrudClient(cc grpc.ClientConnInterface) EmployeeDatabaseCrudClient {
	return &employeeDatabaseCrudClient{cc}
}

func (c *employeeDatabaseCrudClient) CreateEmployee(ctx context.Context, in *NewEmp, opts ...grpc.CallOption) (*Emp, error) {
	out := new(Emp)
	err := c.cc.Invoke(ctx, "/empmgmt.EmployeeDatabaseCrud/CreateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) GetEmployees(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Emps, error) {
	out := new(Emps)
	err := c.cc.Invoke(ctx, "/empmgmt.EmployeeDatabaseCrud/GetEmployees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) UpdateEmployee(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*Emp, error) {
	out := new(Emp)
	err := c.cc.Invoke(ctx, "/empmgmt.EmployeeDatabaseCrud/UpdateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) DeleteEmployee(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/empmgmt.EmployeeDatabaseCrud/DeleteEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeDatabaseCrudServer is the server API for EmployeeDatabaseCrud service.
// All implementations must embed UnimplementedEmployeeDatabaseCrudServer
// for forward compatibility
type EmployeeDatabaseCrudServer interface {
	CreateEmployee(context.Context, *NewEmp) (*Emp, error)
	GetEmployees(context.Context, *Request) (*Emps, error)
	UpdateEmployee(context.Context, *Emp) (*Emp, error)
	DeleteEmployee(context.Context, *Emp) (*Response, error)
	mustEmbedUnimplementedEmployeeDatabaseCrudServer()
}

// UnimplementedEmployeeDatabaseCrudServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeDatabaseCrudServer struct {
}

func (UnimplementedEmployeeDatabaseCrudServer) CreateEmployee(context.Context, *NewEmp) (*Emp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmployee not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) GetEmployees(context.Context, *Request) (*Emps, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployees not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) UpdateEmployee(context.Context, *Emp) (*Emp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmployee not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) DeleteEmployee(context.Context, *Emp) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmployee not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) mustEmbedUnimplementedEmployeeDatabaseCrudServer() {}

// UnsafeEmployeeDatabaseCrudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeDatabaseCrudServer will
// result in compilation errors.
type UnsafeEmployeeDatabaseCrudServer interface {
	mustEmbedUnimplementedEmployeeDatabaseCrudServer()
}

func RegisterEmployeeDatabaseCrudServer(s grpc.ServiceRegistrar, srv EmployeeDatabaseCrudServer) {
	s.RegisterService(&EmployeeDatabaseCrud_ServiceDesc, srv)
}

func _EmployeeDatabaseCrud_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEmp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empmgmt.EmployeeDatabaseCrud/CreateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).CreateEmployee(ctx, req.(*NewEmp))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_GetEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).GetEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empmgmt.EmployeeDatabaseCrud/GetEmployees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).GetEmployees(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_UpdateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Emp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).UpdateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empmgmt.EmployeeDatabaseCrud/UpdateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).UpdateEmployee(ctx, req.(*Emp))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_DeleteEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Emp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).DeleteEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empmgmt.EmployeeDatabaseCrud/DeleteEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).DeleteEmployee(ctx, req.(*Emp))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeDatabaseCrud_ServiceDesc is the grpc.ServiceDesc for EmployeeDatabaseCrud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeDatabaseCrud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "empmgmt.EmployeeDatabaseCrud",
	HandlerType: (*EmployeeDatabaseCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmployee",
			Handler:    _EmployeeDatabaseCrud_CreateEmployee_Handler,
		},
		{
			MethodName: "GetEmployees",
			Handler:    _EmployeeDatabaseCrud_GetEmployees_Handler,
		},
		{
			MethodName: "UpdateEmployee",
			Handler:    _EmployeeDatabaseCrud_UpdateEmployee_Handler,
		},
		{
			MethodName: "DeleteEmployee",
			Handler:    _EmployeeDatabaseCrud_DeleteEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "empmgmt/empmgmt.proto",
}
