// Code generated by protoc-gen-go. DO NOT EDIT.
// source: empmgmt/empmgmt.proto

package exercise

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64603755a12b5ec, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64603755a12b5ec, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Emps struct {
	Emps                 []*Emp   `protobuf:"bytes,1,rep,name=emps,proto3" json:"emps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emps) Reset()         { *m = Emps{} }
func (m *Emps) String() string { return proto.CompactTextString(m) }
func (*Emps) ProtoMessage()    {}
func (*Emps) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64603755a12b5ec, []int{2}
}

func (m *Emps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emps.Unmarshal(m, b)
}
func (m *Emps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emps.Marshal(b, m, deterministic)
}
func (m *Emps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emps.Merge(m, src)
}
func (m *Emps) XXX_Size() int {
	return xxx_messageInfo_Emps.Size(m)
}
func (m *Emps) XXX_DiscardUnknown() {
	xxx_messageInfo_Emps.DiscardUnknown(m)
}

var xxx_messageInfo_Emps proto.InternalMessageInfo

func (m *Emps) GetEmps() []*Emp {
	if m != nil {
		return m.Emps
	}
	return nil
}

type NewEmp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManagerId            int32    `protobuf:"varint,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	DepartmentId         int32    `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEmp) Reset()         { *m = NewEmp{} }
func (m *NewEmp) String() string { return proto.CompactTextString(m) }
func (*NewEmp) ProtoMessage()    {}
func (*NewEmp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64603755a12b5ec, []int{3}
}

func (m *NewEmp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEmp.Unmarshal(m, b)
}
func (m *NewEmp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEmp.Marshal(b, m, deterministic)
}
func (m *NewEmp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEmp.Merge(m, src)
}
func (m *NewEmp) XXX_Size() int {
	return xxx_messageInfo_NewEmp.Size(m)
}
func (m *NewEmp) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEmp.DiscardUnknown(m)
}

var xxx_messageInfo_NewEmp proto.InternalMessageInfo

func (m *NewEmp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewEmp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewEmp) GetManagerId() int32 {
	if m != nil {
		return m.ManagerId
	}
	return 0
}

func (m *NewEmp) GetDepartmentId() int32 {
	if m != nil {
		return m.DepartmentId
	}
	return 0
}

type Emp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManagerId            int32    `protobuf:"varint,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	DepartmentId         int32    `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emp) Reset()         { *m = Emp{} }
func (m *Emp) String() string { return proto.CompactTextString(m) }
func (*Emp) ProtoMessage()    {}
func (*Emp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64603755a12b5ec, []int{4}
}

func (m *Emp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emp.Unmarshal(m, b)
}
func (m *Emp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emp.Marshal(b, m, deterministic)
}
func (m *Emp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emp.Merge(m, src)
}
func (m *Emp) XXX_Size() int {
	return xxx_messageInfo_Emp.Size(m)
}
func (m *Emp) XXX_DiscardUnknown() {
	xxx_messageInfo_Emp.DiscardUnknown(m)
}

var xxx_messageInfo_Emp proto.InternalMessageInfo

func (m *Emp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Emp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Emp) GetManagerId() int32 {
	if m != nil {
		return m.ManagerId
	}
	return 0
}

func (m *Emp) GetDepartmentId() int32 {
	if m != nil {
		return m.DepartmentId
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "empmgmt.Response")
	proto.RegisterType((*Request)(nil), "empmgmt.Request")
	proto.RegisterType((*Emps)(nil), "empmgmt.Emps")
	proto.RegisterType((*NewEmp)(nil), "empmgmt.NewEmp")
	proto.RegisterType((*Emp)(nil), "empmgmt.Emp")
}

func init() { proto.RegisterFile("empmgmt/empmgmt.proto", fileDescriptor_f64603755a12b5ec) }

var fileDescriptor_f64603755a12b5ec = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0xc7, 0x9b, 0x36, 0xaf, 0x7d, 0x99, 0xd7, 0x3e, 0x75, 0x51, 0x08, 0x45, 0x21, 0xac, 0x97,
	0x08, 0x25, 0x85, 0xfa, 0x0d, 0x6c, 0x73, 0xe8, 0xc5, 0x43, 0xc0, 0x8b, 0x97, 0xb2, 0xcd, 0x0e,
	0x25, 0xd0, 0x49, 0xc6, 0xdd, 0x2d, 0xea, 0x87, 0xf4, 0x3b, 0x49, 0x62, 0xac, 0x2d, 0x7a, 0xf6,
	0xb4, 0xbb, 0x33, 0x3f, 0xfe, 0xb3, 0xfc, 0x76, 0xe1, 0x02, 0x89, 0x69, 0x43, 0x6e, 0xda, 0xae,
	0x09, 0x9b, 0xca, 0x55, 0x62, 0xd0, 0x1e, 0x25, 0xc0, 0xdf, 0x0c, 0x2d, 0x57, 0xa5, 0x45, 0x19,
	0xc0, 0x20, 0xc3, 0xa7, 0x1d, 0x5a, 0x27, 0x63, 0xf0, 0x53, 0x62, 0x2b, 0x22, 0xf0, 0x91, 0xd8,
	0x86, 0x5e, 0xd4, 0x8b, 0xff, 0xcd, 0x86, 0xc9, 0x67, 0x4a, 0x4a, 0x9c, 0x35, 0x1d, 0xc9, 0xd0,
	0xbf, 0xc7, 0xe7, 0x94, 0x58, 0xfc, 0x87, 0x6e, 0xa1, 0x43, 0x2f, 0xf2, 0xe2, 0x3f, 0x59, 0xb7,
	0xd0, 0x42, 0x80, 0x5f, 0x2a, 0xc2, 0xb0, 0x1b, 0x79, 0x71, 0x90, 0x35, 0x7b, 0x71, 0x05, 0x40,
	0xaa, 0x54, 0x1b, 0x34, 0xab, 0x42, 0x87, 0xbd, 0x86, 0x0d, 0xda, 0xca, 0x52, 0x8b, 0x6b, 0x18,
	0x69, 0x64, 0x65, 0x1c, 0x61, 0xe9, 0x6a, 0xc2, 0x6f, 0x88, 0xe1, 0x57, 0x71, 0xa9, 0x25, 0x41,
	0xef, 0x17, 0xc7, 0xcd, 0xde, 0x3c, 0x38, 0x4f, 0x89, 0xb7, 0xd5, 0x2b, 0xe2, 0x42, 0x39, 0xb5,
	0x56, 0x16, 0xe7, 0x66, 0xa7, 0xc5, 0x04, 0x82, 0xb9, 0x41, 0xe5, 0xb0, 0xbe, 0xcd, 0xc9, 0x5e,
	0xcd, 0x87, 0x8d, 0xf1, 0x91, 0x2b, 0xd9, 0x11, 0x93, 0x5a, 0xae, 0xd2, 0x35, 0x7b, 0xba, 0x6f,
	0xb5, 0xba, 0xc7, 0xa3, 0x43, 0xd8, 0xca, 0x8e, 0xb8, 0x81, 0xe0, 0x81, 0x75, 0x9b, 0x7d, 0x14,
	0xf5, 0x2d, 0x38, 0x81, 0x60, 0x81, 0x5b, 0xfc, 0x09, 0x3d, 0x3b, 0x18, 0xd4, 0xbe, 0x71, 0xe7,
	0xee, 0xf2, 0x71, 0xbc, 0x31, 0x9c, 0xaf, 0xd8, 0xa8, 0xdc, 0x15, 0x39, 0x26, 0x79, 0x45, 0x53,
	0x7c, 0x41, 0x93, 0x17, 0x16, 0xd7, 0xfd, 0xe6, 0x7f, 0xdc, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0xbb, 0x60, 0x0e, 0x38, 0x02, 0x00, 0x00,
}
